---
- name: Install and Configure Netbox
  hosts: all
  gather_facts: true
  vars:
    netbox_config:
      ALLOWED_HOSTS:
        - "{{ ansible_fqdn }}"
        - "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
        - "{{ ansible_fqdn }}:8443"
        - "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:8443"
      TIME_ZONE: "Europe/Vienna"
    ntp: no
    ldap: no

  tasks:
    - name: set global vars
      set_fact:
        netbox_config: "{{ netbox_config }}"
    - name: install NetworkManager.
      apt:
        name:
          - network-manager
        update_cache: yes
        cache_valid_time: 3600
        state: present
      become: yes
      when:
        - ansible_os_family == "Debian"

- import_playbook: playbooks/pre_tasks.yml
- import_playbook: playbooks/install_chrony.yml
  when:
    - ntp is defined
    - ntp | bool
- import_playbook: playbooks/install_postgresql.yml
- import_playbook: playbooks/install_redis.yml
- import_playbook: playbooks/install_netbox_components.yml
- import_playbook: playbooks/install_http_server.yml
- import_playbook: playbooks/install_ldap_authentication.yml
  when:
    - ldap is defined
    - ldap | bool
