---
- name: Install and configure redis.
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Install redis.
      package:
        name:
          - redis
        state: present

    - name: Ensure redis is running.
      service:
        name: redis.service
        state: started
